name: Auto Table Update

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup Python
      uses: actions/setup-python@v1
      with:
        python-version: '3.x'
        architecture: 'x64'
    - name: Setup pip
      run: |
        python -m pip install --upgrade pip
        pip install pytz
    - name: Run make_table.py
      run: |
        python scripts/update_solution.py
        python scripts/make_table.py
        python scripts/make_readme.py
    - name: Config Github
      run: |
        git config --local user.email "${{ secrets.user_email }}"
        git config --local user.name "${{ secrets.user_name }}"
        git add .
        git commit -m "Auto Update Table (on PUSH event)"
    - name: Push
      uses: ad-m/github-push-action@master
      with:
         branch: 'main'
         github_token: $
